## Each 'number' represents the corresponding day on the advent calendar.
## You may change these to any material name, so long as it remains UPPERCASE.
## Materials which contain more than one word for its name must be separated by an UNDERSCORE
## Example: CHISELED_STONE_BRICK_STAIRS

calendar:
  day_1:
    name: '&3Colored Name Support'
    item: DARK_OAK_LOG
    amount: 1
    enchantments:
      unbreaking: 3
  day_2:
    name: '&9Star of David'
    item: NETHER_STAR
    amount: 1
    enchantments:
      luck_of_the_sea: 1
      sweeping_edge: 3
      mending: 1
    lore:
      - '&aThis is a string list'
      - '&bEvery new line here is a new line of lore'
      - '&cYou can put as many lines as you want'
      - '&dHowever, the more lines you put'
      - '&eThe more cluttered things become.'
    commands:
      - 'lp user %player% permission settemp permissable.node true 24H'